on:
    push:
        branches:
            - '**'
            - "!main"
            - "!release"

jobs:
    build:
        runs-on: [ubuntu-latest]
        steps:
            -   uses: actions/checkout@v4
            -   name: Set up JDK 17

                uses: actions/setup-java@v4
                with:
                    java-version: 17
                    distribution: 'temurin'

            -   uses: actions/cache@v4
                with:
                    path: ~/.m2/repository
                    key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}

            -   name: Installing local dependencies
                run: mvn initialize

            -   name: Build project
                run: mvn -U -B package --file pom.xml

    test:
        needs: build
        runs-on: [ubuntu-latest]
        steps:
            -   uses: actions/checkout@v4
            -   name: Set up JDK 17

                uses: actions/setup-java@v4
                with:
                    java-version: 17
                    distribution: 'temurin'

            -   uses: actions/cache@v4
                with:
                    path: ~/.m2/repository
                    key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}

            -   name: Installing local dependencies
                run: mvn initialize

            -   name: Test project
                run: mvn -B test --file pom.xml
